from app.models import db, Like, environment, SCHEMA

def seed_likes():
    like_1 = Like(user_id=1, post_id=1)
    like_2 = Like(user_id=2, post_id=3)
    like_3 = Like(user_id=2, post_id=5)
    like_4 = Like(user_id=3, post_id=5)
    like_5 = Like(user_id=4, post_id=5)
    like_6 = Like(user_id=1, post_id=5)
    like_7 = Like(user_id=10, post_id=12)
    like_8 = Like(user_id=11, post_id=12)
    like_9 = Like(user_id=9, post_id=12)
    like_10 = Like(user_id=1, post_id=15)
    like_11 = Like(user_id=2, post_id=15)
    like_12 = Like(user_id=3, post_id=15)
    like_13 = Like(user_id=4, post_id=15)
    like_14 = Like(user_id=5, post_id=15)
    like_15 = Like(user_id=6, post_id=15)
    like_16 = Like(user_id=7, post_id=15)
    like_17 = Like(user_id=8, post_id=15)
    like_18 = Like(user_id=9, post_id=15)
    like_19 = Like(user_id=3, post_id=9)
    like_20 = Like(user_id=8, post_id=9)
    like_21 = Like(user_id=9, post_id=9)
    like_22 = Like(user_id=10, post_id=9)
    like_23 = Like(user_id=11, post_id=9)
    like_24 = Like(user_id=2, post_id=9)
    like_25 = Like(user_id=1, post_id=9)

    db.session.add(like_1)
    db.session.add(like_2)
    db.session.add(like_3)
    db.session.add(like_4)
    db.session.add(like_5)
    db.session.add(like_6)
    db.session.add(like_7)
    db.session.add(like_8)
    db.session.add(like_9)
    db.session.add(like_10)
    db.session.add(like_11)
    db.session.add(like_12)
    db.session.add(like_13)
    db.session.add(like_14)
    db.session.add(like_15)
    db.session.add(like_16)
    db.session.add(like_17)
    db.session.add(like_18)
    db.session.add(like_19)
    db.session.add(like_20)
    db.session.add(like_21)
    db.session.add(like_22)
    db.session.add(like_23)
    db.session.add(like_24)
    db.session.add(like_25)
    db.session.commit()


def undo_likes():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.likes RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM likes")

    db.session.commit()
